#!/bin/bash

BIN_DIR="bin"
PID_DIR="/var/run"
PORT='4080'
HOST='localhost'
RUN_AS_USER='nobody'
RUN_AS_GRP='nobody'
DB_PATH='/var/emma'

FILES="block_bitmap db"

function usage {
    echo "Usage: $0 {start|stop|kill|initdb [force]}"
		echo "This is a run control script used to manage the emma database system (emma)."
    exit 1
}

whoami=$(whoami)
if [[ $whoami != "root" ]] 
  then 
    echo "You're not root"
    usage
fi

case "$1" in
  start)
    
    test ! -w  $PID_DIR &&  echo "Can't write to $PID_DIR" && exit 1
    sudo -u $RUN_AS_USER  $BIN_DIR/emma -d $DB_PATH -h $HOST -p $PORT 1>$PID_DIR/emma.pid
    ;;

  stop)
    test ! -e $PID_DIR/emma.pid && echo "No pid file found. Try 'sudo emma_ctl kill' instead" && exit 1
    sudo -u $RUN_AS_USER kill $(<$PID_DIR/emma.pid)        
    sudo rm $PID_DIR/emma.pid
    ;;

  kill)
    sudo killall -u $RUN_AS_USER emma
    sudo rm $PID_DIR/emma.pid &>/dev/null
    ;;


  initdb)

    echo "Path to database files: $DB_PATH"

    if [ "$2" != "force" ]
      then
        for i in $FILES
          do
            test -e $DB_PATH/$i && echo "$DB_PATH/$i exists. Use 'force' or remove the file yourself." && exit 1
          done
    fi

    mkdir -p $DB_PATH 
    chown $RUN_AS_USER:$RUN_AS_GRP $DB_PATH
    sudo -u $RUN_AS_USER test ! -w $DB_PATH && echo "Can't write to $DB_PATH" && exit 1

    sudo -u $RUN_AS_USER dd if=/dev/zero of=$DB_PATH/block_bitmap bs=1024 count=131072
    sudo -u $RUN_AS_USER cat /dev/null >$DB_PATH/db
    chown $RUN_AS_USER:$RUN_AS_GRP $DB_PATH/db
  
    ;;

  *)
    usage
    ;;

esac

